server:
  port: 9002

spring:
  application:
    name: oscars-order-mall
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/oscars_mall?serverTimezone=GMT%2B8

mybatis-plus:
  mapper-locations: com/oscars/mall/order/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

dubbo:
  application:
    name: order-service
  registry:
    address: zookeeper://139.196.166.75:2181
  protocol:
    name: dubbo
    port: 20880